# Generated by Django 6.0.5 on 2026-05-26 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.session'),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
